### ISSUE TITLE
JS Import, Webpack 

### ISSUE THREAD

**Issue by kolesnikova-tavi** [yahoo/intl-messageformat#159]
I'm trying to do that:
```
import IntlMessageFormat from 'intl-messageformat';
import 'intl-messageformat/dist/locale-data/en.js';
import 'intl-messageformat/dist/locale-data/ru.js';
```

`ReferenceError: IntlMessageFormat is not defined`

Version 1.3.0 from npm

**Comment by huy-nguyen** [comment]
If you look at one of the `locale-data` files, you'll see that they are calling `__addLocaleData` on a global `IntlMessageFormat` variable. This of course fails with webpack because it treats every file as a module. You need  to let webpack know that it has to assign the `default` export of the `intl-messageformat` module to a global variable `IntlMessageFormat` by adding the `webpack.ProvidePlugin` in your webpack config:
```javascript
plugins: [
  new webpack.ProvidePlugin({
    IntlMessageFormat: ['intl-messageformat', 'default'],
  }),
// ...
]
```
More info here: https://webpack.js.org/plugins/provide-plugin/.

**Comment by kolesnikova-tavi** [comment]
OK. Thank you!

**Comment by catamphetamine** [comment]
I see you were using `javascript-time-ago` then.
That's a suitable appropriate solution.
In fact, I didn't come up with it until i read this issue.
Added it to the docs.
https://github.com/catamphetamine/javascript-time-ago

**Comment by catamphetamine** [comment]
Still, a better solution would be rewriting `intl-messageformat` so that locale data files are JSON objects instead of executable code.

`IntlMessageFormat.__addLocaleData({"locale":"en","pluralRuleFunction": ...})` -> `[{"locale":"en","pluralRuleFunction": ...}, ...]`.
And `IntlMessageFormat.addLocaleData(require('.../en.js'))` called manually for desired locales.

**Comment by catamphetamine** [comment]
Ok, anyway, I guess time has come for me to use CLDR data directly through `make-plural`
https://github.com/eemeli/make-plural.js
`intl-messageformat` was a good start for me, I learnt many interesting things about CLDR.
`javascript-time-ago` will not depend on `intl-messageformat` and will be using CLDR directly in the new version. That will reduce metadata size also.

**Comment by raix** [comment]
This seems to work
```
new webpack.ProvidePlugin({
  IntlMessageFormat: ["intl-messageformat", "IntlMessageFormat"],
}),
```
