### ISSUE TITLE
Using the number `0` as a value

### ISSUE THREAD

**Issue by jerrysu** [yahoo/intl-messageformat#88]
Hi, with the following code:

```js
var IntlMessageFormat = require('intl-messageformat');

var msg = new IntlMessageFormat('Days left: {days}', 'en-US');
console.log(msg.format({days: 0}));
```

Expected output: `"Days left: 0"`
Actual output: `"Days left: "`

This line seems to be the culprit: https://github.com/yahoo/intl-messageformat/blob/master/src/compiler.js#L157

**Comment by ericf** [comment]
Values for arguments with no specified format, like what you have, are assumed to be strings. If you want to format `days` as a number, the specify it like this: `{days, number, integer}`

**Comment by jerrysu** [comment]
I feel that it is somewhat misleading because using any non-zero number in the above example works as one would expect. I understand that being more specific of the variable type is what is currently required to make the above work, but I'm afraid people will only learn of this requirement after discovering bugs in their code (as I did).

If `StringFormat.prototype.format(value)` assumes `value` is a string, shouldn't it reject objects, arrays, and other "truthy" non-string objects rather than try to cast them to strings?

Since I have a wrapper around `IntlMessageFormat` in my code, I am working around this now by casting `0` to a string, but this is not the solution I was hoping for in the longer term.

**Comment by santiagoaguiar** [comment]
Just been bitten by this one. I think there should be, at least, a warning. 

I bet someone will at some point add another `{count}` somewhere on our code without remembering that, though it works for > 0, it doesn't for 0. There's no way we can't catch this one with a linter or something either I think, unless we could have an explicit way to say `{name, string}` and check that every replacement has an specified type.

How do you guys actually avoid these kind of bugs? :)

**Comment by bjbrewster** [comment]
I too have just been bitten by this and I can only imagine the number of duplicate bug reports by others. I believe this is an issue due it being inconsistent.  As long the value supports toString() then it should be inserted, even if it's value is 0.  I'm trying hard to not imagine the underlying test for this is `if (!value) ...` instead of comparing to null or undefined.  If every other number does not require special formatting then 0 should not as well.  

Can you give anything but a contrived example otherwise?

**Comment by scriby** [comment]
Just got bit by this one as well.

The current behavior is extremely surprising for end users of this library who do not have perfect knowledge of its inner workings and intents of its authors.

I agree with prior suggestions that if the behavior is desired to not allow numbers to be inserted without specifically specifying that it is a number in the localization string, then it should error in all cases, instead of silently fail only when 0 is inserted.

It would also be acceptable for the string formatter to automatically coerce the argument to a string instead.
