### ISSUE TITLE
Newer version (1.0.2) causes 'No locale data has been added to IntlMessageFormat for: ' error

### ISSUE THREAD

**Issue by dignatjew** [yahoo/intl-messageformat#89]
The error is thrown by core.js in line 251. With the 1.0.1 version, no error occurs.

**Comment by ericf** [comment]
Can you provide some more details and a simplified reproducible examples?

**Comment by jerrysu** [comment]
@dignatjew: See https://github.com/yahoo/intl-messageformat/releases/tag/v1.0.2

If you're using `Browserify` or `Webpack`, you'll need to find a way to load the locale-specific data (or load them all, if you want). The locale data can be found in https://github.com/yahoo/intl-messageformat/tree/master/dist/locale-data.

Otherwise, you can also look at how the package https://github.com/yahoo/grunt-extract-cldr-data pulls the data from https://github.com/papandreou/node-cldr and come up with your own strategy to load this data.

**Comment by athibaud** [comment]
with webpack you can use the [expose-loader](https://github.com/webpack/expose-loader) and to do something like:

```js
require('expose?IntlMessageFormat!intl-messageformat');
require('intl-messageformat/dist/locale-data/fr');
```

**Comment by ericf** [comment]
I'm closing this, but it can be reopened if there's a reproducible example added.
