### ISSUE TITLE
Infinity support ?

### ISSUE THREAD

**Issue by nfroidure** [yahoo/intl-messageformat#93]
I'd like to use message format with Infinity. Something like that:
```js
message = 'You have {storageAmount, plural, one {a gigabyte of} other {# gigabytes of} infinity {an unlimited}} data storage available'
```

It seems possible according to [the spec](
http://cldr.unicode.org/index/cldr-spec/plural-rules):
Choosing Plural Category Names
8 - If there are more categories needed for the language, describe what those categories need to cover in the bug report.

**Comment by ericf** [comment]
Yup, it's possible! Since you have a specific number value (`Infinity`) you can construct your message like this:

```
You have {storageAmount, plural,
  =Infinity {an unlimited}
  one {a gigabyte of}
  other {# gigabytes of}
} data storage available'
```

```js
message.format({amount: Infinity});
```

The `=Infinity` will cause Intl MessageFormat to check if the `amount` variable's string value equals what's after `=`. [Here's the implementation](https://github.com/yahoo/intl-messageformat/blob/master/src/compiler.js#L171-177) if you're interested.

**Comment by nfroidure** [comment]
Oh, nice. Thank you for the clear explanation. Have a nice day.
