### ISSUE TITLE
Build is failing due to saucelabs

### ISSUE THREAD

**Issue by jasonmit** [yahoo/intl-messageformat#97]
Build is failing due to saucelabs

```
saucelabs testing does not work with pull requests
The command "npm run travis" exited with 0.
```

**Comment by juandopazo** [comment]
Not a bug.

The last commit-to-master build is passing. The last two pull request builds are failing because it *is* actually running the Saucelabs tests. The reason it is running them is because the origin branch is in the same repository as `master`. That's basically a trick to enable testing in Saucelabs in pull requests when the sender of the pull request has write access to the repository. If you want the Saucelabs build disabled, send the pull request from a fork.

**Comment by jasonmit** [comment]
The only reason I'm reporting is because the badge is indicating it's failing.  

https://www.dropbox.com/s/lm5i04fak1apr77/Screenshot%202015-02-09%2012.46.12.png?dl=0

**Comment by ericf** [comment]
Yeah this is Sauce being flaky :(
